acme_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }
    requirements:
      name: (show^)
acme_store_show:
    pattern: /hello/show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show, id: 1}
    requirements:
        id: \d+
acme_store_delete:
    pattern: /hello/delete/{id}
    defaults: {_controller: AcmeStoreBundle:Default:delete}
acme_store_query:
    pattern: /hello/query/{id}
    defaults: {_controller: AcmeStoreBundle:Default:query}
acme_sotre_create:
    pattern: /hello/create
    defaults: {_controller: AcmeStoreBundle:Default:create}
