login:
  path: /login
  defaults: { _controller:AcmeSecurityBundle:Security:login }
  
login_check:
  path: /login_check
  
acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

ssstrz_test:
    resource: "@SsstrzTestBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

