parameters:
#    ssstrz_test.example.class: Ssstrz\TestBundle\Example

services:
#    ssstrz_test.example:
#        class: %ssstrz_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
